start_year: 1960
end_year: 2020
start_month: 1
end_month: 12
frequency: "D" # file frequency. Currently supports "M" for monthly files, "D" for daily
skipdates: # skip files the following dates in their filenames, YYYY-MM-DD
  - "1961"
  - "1962"
  - "1963"
  - "1964"
  - "1966"
  - "1967"
  - "1968"
  - "1969"
  - "1971"
  - "1972"
  - "1973"
  - "1974"
  - "1976"
  - "1977"
  - "1978"
  - "1979"
  - "1981"
  - "1982"
  - "1983"
  - "1984"
  - "1986"
  - "1987"
  - "1988"
  - "1989"
  - "1991"
  - "1992"
  - "1993"
  - "1994"
  - "1996"
  - "1997"
  - "1998"
  - "1999"
  - "2001"
  - "2002"
  - "2003"
  - "2004"
  - "2006"
  - "2007"
  - "2008"
  - "2009"
  - "2011"
  - "2012"
  - "2013"
  - "2014"
  - "2016"
  - "2017"
  - "2018"
  - "2019"
input_dir: "/work/scratch-pw5/mattjbr"
filename: "wrfout_d03_{start_date}"
file_type: "netcdf3" # only needed if the files are not netcdf4 (most now are)
varnames:
  - "Q2"
  - "T2"
  - "PSFC"
  - "U10"
  - "V10"
  - "RAINC"
  - "RAINNC"
  - "SWDOWN"
  - "GLW"
date_format: "%Y-%m-%d_%H:%M:%S" # use python datestring formatting codes https://docs.python.org/3/library/datetime.html#format-codes
target_root: "/work/scratch-pw5/mattjbr/output"
store_name: "dataset3_fulloutput_1960-2020.zarr"
concatdim: "Time" # name of the dimension that the individual files will be concatenated along. Usually "time". Note this is separate to the merging of variables stored in separate files, which is handled by varnames
concatvar: "XTIME" # name of the VARIABLE that contains the time coordinates in each file, used for the concatenation. Usually it is the same as concatdim. 
target_chunks: 
  Time: 8760
  south_north: 18
  west_east: 18
num_workers: 16 # above 1 is experimental...
prune: 0 # no. of files to process, set to 0 to use all
overwrites: "off" # "on" or "off"
var_overwrites:
#  - "lat"
#  - "lon"
overwrite_source:
